#!/usr/bin/env python
########################################################################
#
# PDFgui            by DANSE Diffraction group
#                   Simon J. L. Billinge
#                   (c) 2006 trustees of the Michigan State University.
#                   All rights reserved.
#
# File coded by:    Chris Farrow
#
# See AUTHORS.txt for a list of people who contributed.
# See LICENSE.txt for license information.
#
########################################################################

# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Wed Mar 29 13:54:14 2006

import wx
from pdfpanel import PDFPanel

class JournalPanel(wx.Panel, PDFPanel):
    def __init__(self, *args, **kwds):
        PDFPanel.__init__(self)
        # begin wxGlade: JournalPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.journalTextCtrl = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.exportButton = wx.Button(self, -1, "Export")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.onText, self.journalTextCtrl)
        self.Bind(wx.EVT_BUTTON, self.onExport, self.exportButton)
        # end wxGlade
        self.__customProperties()

    def __set_properties(self):
        # begin wxGlade: JournalPanel.__set_properties
        self.journalTextCtrl.SetMinSize((450, 450))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JournalPanel.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.journalTextCtrl, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_2.Add((1, 1), 1, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.exportButton, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade

    def __customProperties(self):
        """Custom Properties go here."""
        self.dirname = ""
        self.filename = ""

    def onText(self, event): # wxGlade: JournalPanel.<event_handler>
        """Record anything that is written into the journal."""
        self.mainFrame.control.journal = event.GetString()
        self.mainFrame.needsSave()
        return

    def onExport(self, event): # wxGlade: JournalPanel.<event_handler>
        """Export the journal to an external file."""
        matchstring = "Text files (*.txt)|*.txt|All Files|*"
        d = wx.FileDialog(None, "Export to...",
                self.dirname, self.filename, matchstring, 
                wx.SAVE|wx.OVERWRITE_PROMPT)

        if d.ShowModal() == wx.ID_OK:
            import os.path
            self.dirname = d.GetDirectory()
            self.filename = d.GetFilename()
            fullpath = os.path.join(self.dirname, self.filename)
            outfile = open(fullpath, 'w')
            outfile.write(self.mainFrame.control.journal)
            outfile.close()
        d.Destroy()
        return

    # Methods overloaded from PDFPanel
    def refresh(self):
        """Fill the jounalTextCtrl with the journal."""
        self.journalTextCtrl.SetValue(self.mainFrame.control.journal)
# end of class JournalPanel

__id__ = "$Id$"
