{% set setupdata = load_setup_py_data() %}

package:
  name: diffpy.pdfgui
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/diffpy.pdfgui.git
  git_url: ..

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  entry_points:
    - pdfgui = diffpy.pdfgui.applications.pdfgui:main

  osx_is_app: True

app:
  entry: pdfgui                                         [not win]
  entry: pythonw -m diffpy.pdfgui.applications.pdfgui   [win]
  icon: pdfgui_64x64.png
  summary: materials structure analysis from Pair Distribution Function

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - six
    - matplotlib
    - wxpython 4.*
    - menuinst                  [win]
    - diffpy.pdffit2
    - diffpy.structure >=3
    - diffpy.utils

test:
  # Python imports
  imports:
    - diffpy.pdfgui.tui
    - diffpy.pdfgui.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.pdfgui
  summary: GUI for PDF simulation and structure refinement
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
