#!/usr/bin/env python
# -*- coding: UTF-8 -*-
##############################################################################
#
# PDFgui            by DANSE Diffraction group
#                   Simon J. L. Billinge
#                   (c) 2006 trustees of the Michigan State University.
#                   All rights reserved.
#
# File coded by:    Chris Farrow
#
# See AUTHORS.txt for a list of people who contributed.
# See LICENSE.txt for license information.
#
##############################################################################

# generated by wxGlade 0.6.3 on Wed Mar 11 13:17:19 2009

import wx
from diffpy.pdfgui.gui.pdfguiglobals import iconpath
from diffpy.pdfgui.gui.pdfpanel import PDFPanel


class WelcomePanel(wx.Panel, PDFPanel):
    def __init__(self, *args, **kwds):
        PDFPanel.__init__(self)
        wx.Panel.__init__(self, *args, **kwds)
        kwds["style"] = wx.TAB_TRAVERSAL
        bitmap = wx.Bitmap(iconpath("titlepage.png"))
        self.bitmap_1 = wx.StaticBitmap(self, -1, bitmap)

        self.__set_properties()
        self.__do_layout()
        return

    def __set_properties(self):
        return

    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.bitmap_1, 0,
            wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_2, 1,
            wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        return

    # Methods overloaded from PDFPanel
    def refresh(self):
        return

# end of class WelcomePanel
